apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: microservices-discovery
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints", "pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: microservices-discovery-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: microservices-discovery
subjects:
  - kind: ServiceAccount
    name: default
    namespace: ms
