apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ms-ingress
  namespace: ms
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/users`)
      kind: Rule
      services:
        - name: user-service
          port: 8081
    - match: PathPrefix(`/products`)
      kind: Rule
      services:
        - name: product-service
          port: 8082
    - match: PathPrefix(`/orders`)
      kind: Rule
      services:
        - name: order-service
          port: 8083
