apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-users
  namespace: ms
spec:
  stripPrefix:
    prefixes:
      - /users
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-products
  namespace: ms
spec:
  stripPrefix:
    prefixes:
      - /products
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-orders
  namespace: ms
spec:
  stripPrefix:
    prefixes:
      - /orders
